### ISSUE TITLE
华为ROM存在一个额外的广播注册数量限制

### ISSUE THREAD

**Issue by uccmawei** [android-in-china/Compatibility#10]
* 设备厂商：华为，荣耀
* 设备型号：荣耀V8，荣耀DUK AL20，华为MHA AL00
* 设备 ROM：（请勿在此反馈社区 ROM 的相关问题）
* Android 版本：7.0， 8.0
* 涉及的 Android API：context.registerReceiver(receiver, intentFilter)
* 预期表现：不限制广播接收器的数量
* 实际表现：一般APP限制在500以内，超过就报错。
* 相关 logcat 日志：
07-20 16:42:36.590 10500-10500/com.test.demo E/LoadedApk: com.test.demo registered 501 Receivers  in 2 Contexts
    java.lang.Throwable
        at android.app.LoadedApk.checkRecevierRegisteredLeakLocked(LoadedApk.java:1009)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1038)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1476)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1456)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1450)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
        at com.test.demo.TestActivity$2.onClick(TestActivity.java:283)
        at android.view.View.performClick(View.java:5646)
        at android.view.View$PerformClick.run(View.java:22473)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
* 补充说明：
该限制存在一个白名单，微信在名单中
参考文档：
https://blog.csdn.net/llew2011/article/details/79054457

**Comment by Trumeet** [comment]
貌似是 App 端的限制，不知道能否通过特殊方法解除..（没用过华为 rom，瞎写..

**Comment by xgeeek** [comment]
在项目中用了一段时间，有效

**Comment by asLody** [comment]
https://github.com/asLody/VirtualApp/blob/master/VirtualApp/lib/src/main/java/com/lody/virtual/server/am/BroadcastSystem.java#L101

**Comment by nitrohsu** [comment]
这个问题确实存在，建议通过反射将自家App ApplicationId 注入白名单或者将限制数量扩展；
核心问题还是减少App的广播注册监听量，这对系统的耗电也有好处。
