### ISSUE TITLE
多个厂商 ROM 拦截 Provider 跨进程调用

### ISSUE THREAD

**Issue by Trumeet** [android-in-china/Compatibility#12]
* 设备厂商：
小米、一加、三星、华为等
* 设备型号：（可列举多个型号，不必覆盖全部有此问题的型号）
小米 6、小米 8 等。
* 设备 ROM：（请勿在此反馈社区 ROM 的相关问题）
没有统计，可能性最大的是官方 ROM。
* Android 版本：
Android L ~ Android O
* 涉及的 Android API：（请尽可能全面的列举或描述涉及到的 API）
`ContentResolver` 的所有跨进程调用（增删改查及 `call`）
* 预期表现：
对方 Provider 回调。
* 实际表现：
抛出异常，显示为找不到 URI（实则有且启用）
* 相关 logcat 日志：
```
Fatal Exception: java.lang.IllegalArgumentException: Unknown URI content://com.xiaomi.xmsf.push.control.APIProvider
       at android.content.ContentResolver.call(ContentResolver.java:1721)
       at top.trumeet.common.push.ControllerImpl.call(ControllerImpl.java:28)
       at top.trumeet.common.push.ControllerImpl.setEnable(ControllerImpl.java:54)
       at top.trumeet.mipushframework.MainFragment.lambda$initSwitch$0$MainFragment(MainFragment.java:203)
       at top.trumeet.mipushframework.MainFragment$$Lambda$0.onCheckedChanged(Unknown Source:2)
       at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
       at android.support.v7.widget.SwitchCompat.setChecked(SwitchCompat.java:1056)
       at android.support.v7.widget.SwitchCompat.toggle(SwitchCompat.java:1051)
       at android.widget.CompoundButton.performClick(CompoundButton.java:132)
       at android.view.View$PerformClick.run(View.java:24803)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6650)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)
```
* 补充说明：
[http://crashes.to/s/19a9ba6f4df](http://crashes.to/s/19a9ba6f4df)

一加 ROM 有一个 「高级优化」，开启后被 Android 电池优化的应用都会受到此限制。现在暂时解决方案是强制用户去除优化。

**Comment by oasisfeng** [comment]
是否跨应用？

**Comment by Trumeet** [comment]
@oasisfeng 是跨应用

**Comment by Cryolitia** [comment]
`ContentProvider`几乎是Android N以上Xposed模块与宿主通信的唯一手段，现已有大量用户（主要是MIUI，亦有一加、魅族）反馈此跨应用通信问题。
